<!--
README: Bluefin Wolves Teaser Landing Page Component
===================================================
- Page Path: projectbluefin.io/wolves
- Comic Content: Delegated to WolvesComicReader.vue. PDF URL is managed
  by the component itself (BASE_URL + color-with-bluefin.pdf).
- Quotes: Sourced from `src/data/bazzite-quotes.json` with fields
  `quote`, `attribution`, optional `context`, and optional `date`.
  Real approved Discord quotes should replace placeholder lorem ipsum values in that file.
- Donate QR Code: Generated by `scripts/generate-qrs.js` and currently points to `#`.
  Replace `donateUrl` in `scripts/generate-qrs.js` and re-run the script when the real URL is ready.
- Playlist ID in use: `PLA78oiE-RGAE` ("Bluefin: Seven Days to the Wolves" on YouTube).
- Playback approach: click-to-start in-page YouTube playlist player + visible YouTube Music deep link.
  We do not attempt auth-state detection because YouTube sign-in/Premium status cannot be reliably verified in-browser.
- Future Spotify support: add a Spotify URI/provider adapter in `src/data/wolves-playlist.json`
  and `WolvesSoundtrack.vue` without redesigning page layout.
-->
<script setup lang="ts">
import type { WolvesChapter } from './data/wolves-story'
import { computed, ref } from 'vue'
import TopNavbar from './components/TopNavbar.vue'
import WolvesComicReader from './components/wolves/WolvesComicReader.vue'
import WolvesLoreColumn from './components/wolves/WolvesLoreColumn.vue'
import WolvesQrCodes from './components/wolves/WolvesQrCodes.vue'
import WolvesSoundtrack from './components/wolves/WolvesSoundtrack.vue'
import { wolvesRelease } from './data/wolves-story'
import { getChapterForPage } from './utils/wolvesStory'

// Soundtrack playback and comic autoplay state
const isPlaying = ref(false)

// Current page (1-based) tracked here so the chapter can be passed to WolvesSoundtrack.
const currentPage = ref(1)
const activeChapter = computed<WolvesChapter | undefined>(() => getChapterForPage(currentPage.value))

const loreColumnRef = ref<any>(null)
const isLoreCopied = ref(false)

function handlePrevLore() {
  loreColumnRef.value?.prevLore()
}

function handleNextLore() {
  loreColumnRef.value?.nextLore()
}

function handleShareLore() {
  loreColumnRef.value?.shareLore()
}

function handleCopiedStatus(status: boolean) {
  isLoreCopied.value = status
}

function handleTrackChange(index: number) {
  if (index === 0) {
    currentPage.value = 1
  }
  else if (index === 1) {
    currentPage.value = 6
  }
  else if (index === 6) {
    currentPage.value = 11
  }
}

// Console Email Submission
const emailInput = ref('')
const isSubmittingEmail = ref(false)
const emailSubmitted = ref(false)
const emailFeedback = ref('')

function handleEmailSubmit() {
  if (!emailInput.value || !emailInput.value.includes('@')) {
    emailFeedback.value = 'Error from server (BadRequest): invalid email coordinate'
    return
  }
  isSubmittingEmail.value = true
  emailFeedback.value = 'kubectl rollout status deployment/comms-relay-agent -n bazzite'
  setTimeout(() => {
    isSubmittingEmail.value = false
    emailSubmitted.value = true
    emailFeedback.value = 'deployment "comms-relay-agent" successfully rolled out // CONNECTION SECURED.'
  }, 1500)
}

// Background Wallpaper State
const playlistCurrentTime = ref(0)
const playlistDuration = ref(0)
const playlistTrackIndex = ref(0)
const isSoundtrackActive = ref(false)

function handleProgress(data: { currentTime: number, duration: number, playlistIndex: number }) {
  playlistCurrentTime.value = data.currentTime
  playlistDuration.value = data.duration
  playlistTrackIndex.value = data.playlistIndex
  isSoundtrackActive.value = true
}

const totalProgress = computed(() => {
  if (!isSoundtrackActive.value || playlistDuration.value <= 0) {
    return 0
  }
  const trackProgress = playlistCurrentTime.value / playlistDuration.value
  return Math.min(1, Math.max(0, (playlistTrackIndex.value + trackProgress) / 7))
})

const currentPairIndex = computed(() => {
  if (!isSoundtrackActive.value) {
    return 9 // Pair 10 by default
  }
  const wallpaperIndexFloat = totalProgress.value * 12
  return Math.floor(wallpaperIndexFloat) % 12
})

const nightOpacity = computed(() => {
  if (!isSoundtrackActive.value) {
    return 1.0 // Full night by default
  }
  const wallpaperIndexFloat = totalProgress.value * 12
  const localProgress = wallpaperIndexFloat - Math.floor(wallpaperIndexFloat)
  return Math.sin(localProgress * Math.PI)
})

const dayWallpaperUrl = computed(() => {
  const pairStr = String(currentPairIndex.value + 1).padStart(2, '0')
  return `url('${import.meta.env.BASE_URL}img/wallpapers/bluefin-${pairStr}-day.webp')`
})

const nightWallpaperUrl = computed(() => {
  const pairStr = String(currentPairIndex.value + 1).padStart(2, '0')
  return `url('${import.meta.env.BASE_URL}img/wallpapers/bluefin-${pairStr}-night.webp')`
})
</script>

<template>
  <div class="wolves-teaser-page">
    <!-- Dynamic Wallpaper Background Layers -->
    <div class="wallpaper-container">
      <div class="wallpaper-layer day-layer" :style="{ backgroundImage: dayWallpaperUrl }" />
      <div class="wallpaper-layer night-layer" :style="{ backgroundImage: nightWallpaperUrl, opacity: nightOpacity }" />
    </div>

    <!-- Top Global Navigation Bar -->
    <TopNavbar />

    <!-- Main Outer Container -->
    <div class="wolves-layout">
      <!-- SECTION 1: HERO SECTION -->
      <header class="wolves-hero">
        <div class="hero-text">
          <!-- Aggressive display typography with heavy scale -->
          <h1 class="hero-title">
            Seven Days to the <span class="accent">Wolves</span>
          </h1>
          <p class="hero-description">
            In the distant future, open source maintainers are not only sought after, they are hunted. Enslaved by the very machines they created, betrayed by the societies they swore to protect. They fight alone.

            <br><br>Our Childhood's End, is their beginning.

            <br><br>A fundraising effort to immortalize contributors in legend. Issue sponsorships available.
          </p>
          <div class="hero-footnote">
            Coming 2027
          </div>
        </div>
      </header>

      <!-- Two-column desktop layout: Comic Reader on the left, a pinned
           Soundtrack Widget + Bazzite Dispatch sidebar on the right. Falls
           back to a single vertical stack below 1024px. -->
      <div class="content-grid">
        <div class="col-left">
          <!-- SECTION 2: COMIC READER -->
          <WolvesComicReader
            :chapters="wolvesRelease.chapters"
            :autoplay="isPlaying"
            @update:page="currentPage = $event"
          />

          <!-- Soundtrack Control Widget (Moved below slides, expanded) -->
          <WolvesSoundtrack
            v-model:playing="isPlaying"
            :chapter="activeChapter"
            :lore-copied="isLoreCopied"
            @track-change="handleTrackChange"
            @prev-lore="handlePrevLore"
            @next-lore="handleNextLore"
            @share-lore="handleShareLore"
            @progress="handleProgress"
          />
        </div>

        <div class="col-right">
          <WolvesLoreColumn
            ref="loreColumnRef"
            :chapter="activeChapter"
            @copied-status="handleCopiedStatus"
          />

          <!-- Decryption Status Meter -->
          <div class="decryption-meter-card">
            <div class="meter-header">
              <span class="meter-title font-mono">DECRYPTION_STATUS // CHAPTER_02</span>
              <span class="meter-percentage font-mono">7%</span>
            </div>
            <div class="meter-bar-container">
              <div class="meter-bar-fill" style="width: 7%" />
            </div>
            <p class="meter-details font-mono">
              Operatives active: 1,337 // Decoding node: PROMETHEUS-7
            </p>
          </div>
        </div>
      </div>

      <!-- SECTION 4: COMMUNITY & CONVERSION (Console + Discord) -->
      <section id="wolves-support" class="comic-reader-section">
        <div class="support-wrap">
          <h2 class="title-h2">
            Establish Secure Channel
          </h2>
          <p class="title-p">
            Subscribe to receive decrypted transmissions and critical notifications when Chapter 1 launches. Or connect to the operative mesh directly on Discord.
          </p>
        </div>

        <div class="community-console-grid">
          <!-- Terminal Newsletter Console -->
          <div class="terminal-console-card">
            <div class="console-header">
              <span class="console-title font-mono">nimbinatus@blue-universal:~</span>
              <div class="gnome-window-controls">
                <button class="gnome-control-btn minimize" aria-label="Minimize" tabindex="-1" type="button">
                  <svg width="12" height="12" viewBox="0 0 12 12"><rect x="2" y="5.5" width="8" height="1" fill="currentColor" /></svg>
                </button>
                <button class="gnome-control-btn maximize" aria-label="Maximize" tabindex="-1" type="button">
                  <svg width="12" height="12" viewBox="0 0 12 12"><rect x="2.5" y="2.5" width="7" height="7" rx="0.5" fill="none" stroke="currentColor" stroke-width="1" /></svg>
                </button>
                <button class="gnome-control-btn close" aria-label="Close" tabindex="-1" type="button">
                  <svg width="12" height="12" viewBox="0 0 12 12"><path d="M2.5 2.5 L9.5 9.5 M9.5 2.5 L2.5 9.5" stroke="currentColor" stroke-width="1" stroke-linecap="round" /></svg>
                </button>
              </div>
            </div>
            <div class="console-body">
              <p class="console-text font-mono text-cyan">
                nimbinatus@blue-universal:~$ kubectl apply -f bazzite-comms.yaml
              </p>
              <p class="console-text font-mono text-green">
                configmap/bazzite-comms-config created
                <br>deployment.apps/comms-relay-agent created
              </p>
              <p class="console-text font-mono text-gray">
                [SYSTEM] Enter operative email to launch deployment:
              </p>

              <form v-if="!emailSubmitted" class="console-form" @submit.prevent="handleEmailSubmit">
                <span class="console-prompt font-mono">&gt;</span>
                <input
                  v-model="emailInput"
                  type="email"
                  placeholder="operative@domain.xyz"
                  class="console-input font-mono"
                  :disabled="isSubmittingEmail"
                  required
                >
                <button
                  type="submit"
                  class="console-submit-btn font-mono"
                  :disabled="isSubmittingEmail"
                >
                  [ APPLY ]
                </button>
              </form>

              <div v-if="emailFeedback" class="console-feedback font-mono" :class="{ success: emailSubmitted }">
                {{ emailFeedback }}
              </div>
            </div>
          </div>

          <!-- Encrypted Discord Invite Card -->
          <div class="discord-invite-card">
            <h3 class="discord-title font-mono">
              [ SECURE_MESH_LINK ]
            </h3>
            <p class="discord-desc">
              Connect to the live mesh. Chat with core maintainers, coordinate Linux workstation factory builds, and decrypt incoming lore with the community.
            </p>
            <div class="discord-action-wrap">
              <a
                href="https://discord.gg/projectbluefin"
                target="_blank"
                rel="noopener noreferrer"
                class="discord-btn"
              >
                JOIN THE MESH (DISCORD) &rarr;
              </a>
              <span class="discord-coords font-mono">COORDS: 42.109 / -83.045 // MESH_ACTIVE</span>
            </div>
          </div>
        </div>

        <div class="support-links font-mono">
          <a href="https://store.projectbluefin.io" target="_blank" rel="noopener noreferrer">STORE_ACCESS</a>
          <span class="separator">|</span>
          <a href="https://docs.projectbluefin.io/donations" target="_blank" rel="noopener noreferrer">DONATE_FUNDS</a>
        </div>
      </section>

      <section class="wolves-page-qr comic-reader-section">
        <WolvesQrCodes />
      </section>
    </div>
  </div>
</template>

<style scoped lang="scss">
.wallpaper-container {
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  overflow: hidden;
  pointer-events: none;
  z-index: 0;
}

.wallpaper-layer {
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  background-size: 100% auto;
  background-position: top center;
  background-repeat: repeat-y;
  transition: background-image 1s ease-in-out;
  pointer-events: none;
}

.day-layer {
  z-index: 1;
}

.night-layer {
  z-index: 2;
  transition:
    background-image 1s ease-in-out,
    opacity 0.5s ease-in-out;
}

.wolves-teaser-page {
  background-color: #0c1016;
  min-height: 100vh;
  position: relative;
  // Firefox can break sticky descendants when an ancestor creates a scrolling
  // container via overflow. `clip` prevents horizontal bleed without that side
  // effect.
  overflow-x: clip;
  box-sizing: border-box;

  &::after {
    content: '';
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    height: 600px;
    background: linear-gradient(to bottom, rgba(12, 16, 22, 0.7), transparent);
    z-index: 2;
    pointer-events: none;
  }
}

.wolves-layout {
  position: relative;
  z-index: 3;
  max-width: 1280px;
  margin: 0 auto;
  padding: 32px 24px 80px;
  display: flex;
  flex-direction: column;
  gap: 32px;
}

.wolves-page-qr {
  margin-top: 8px;
}

// Two-column desktop grid: Comic Reader (left) + pinned Soundtrack Widget /
// Bazzite Dispatch sidebar (right). Falls back to a vertical stack below
// 1024px.
.content-grid {
  display: flex;
  flex-direction: column;
  gap: 16px;
  width: 100%;

  @media (min-width: 1024px) {
    display: grid;
    grid-template-columns: 2fr 1fr;
    align-items: stretch;
    gap: 16px;
  }
}

.col-left {
  min-width: 0;
  display: flex;
  flex-direction: column;
  gap: 16px;
  height: 100%;

  // Left-align the comic reader within its column instead of the
  // page-wide auto-centering used when the reader is the sole column.
  :deep(.comic-viewport),
  :deep(.scroll-comic-layout),
  :deep(.reader-controls),
  :deep(.sidebar-soundtrack-card) {
    margin-left: 0;
    margin-right: 0;
    max-width: 100%;
    width: 100%;
  }
}

.col-right {
  min-width: 0;
  display: flex;
  flex-direction: column;
  gap: 16px;

  @media (min-width: 1024px) {
    height: 100%;
  }
}

// Persistent Floating Soundtrack Widget (markup moved to WolvesSoundtrack component)
// Mobile: reserve space at the bottom of the page for the fixed player bar,
// but only while the bar is actually visible (class toggled by WolvesSoundtrack).
:global(.wolves-player-active) .wolves-layout {
  @media (max-width: 767px) {
    padding-bottom: calc(88px + env(safe-area-inset-bottom));
  }
}

// Hero Section
.wolves-hero {
  display: flex;
  flex-direction: column;
  gap: 20px;
  padding: 24px 0 20px;
  border-bottom: 1px solid rgba(var(--color-blue-rgb), 0.2);

  .hero-text {
    text-align: center;

    @media (min-width: 768px) {
      text-align: left;
    }
  }

  .hero-title {
    font-size: clamp(2.8rem, 4.8vw, 4.2rem);
    font-weight: 800;
    letter-spacing: -0.03em;
    line-height: 1.1;
    text-transform: uppercase;
    margin-bottom: 12px;

    @media (min-width: 768px) {
      font-size: clamp(3.8rem, 5.8vw, 5.2rem);
    }

    .accent {
      color: var(--color-blue);
    }
  }

  .hero-description {
    font-size: 1.3rem;
    line-height: 1.6;
    color: #bdbdbd;
    margin-bottom: 12px;
    max-width: 600px;
  }

  .hero-footnote {
    font-size: 1rem;
    color: rgba(189, 189, 189, 0.6);
    font-style: italic;
  }
}

@keyframes pulse {
  0% {
    transform: scale(1);
    opacity: 0.8;
  }
  50% {
    transform: scale(1.1);
    opacity: 1;
  }
  100% {
    transform: scale(1);
    opacity: 0.8;
  }
}

.dispatch-quote-section {
  @media (min-width: 1024px) {
    flex: 1;
    display: flex;
    flex-direction: column;
  }
}

// Intercepted communications section
.dispatch-quote-card {
  background-color: #10151f;
  border: 1px solid #272727;
  padding: 16px;
  border-radius: 16px;
  display: flex;
  flex-direction: column;
  gap: 16px;
  position: relative;
  width: 100%;
  box-shadow: 0 10px 25px rgba(0, 0, 0, 0.3);
  transition:
    border-color 0.3s,
    box-shadow 0.3s;

  @media (min-width: 1024px) {
    flex: 1;
  }

  &:hover {
    border-color: rgba(var(--color-blue-rgb), 0.4);
    box-shadow: 0 10px 25px rgba(0, 0, 0, 0.3);
  }
}

.dispatch-plan-content {
  font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono', 'Courier New', monospace;
  background: linear-gradient(180deg, rgba(16, 21, 31, 0.98) 0%, rgba(12, 16, 22, 0.98) 100%);
  border: 1px solid rgba(var(--color-blue-rgb), 0.22);
  border-radius: 10px;
  padding: 12px 14px;
  box-shadow: inset 0 1px 0 rgba(255, 255, 255, 0.05);

  @media (min-width: 480px) {
    padding-right: 192px;
  }
}

.dispatch-plan-command {
  margin: 0 0 6px;
  font-size: 0.86rem;
  color: rgba(189, 189, 189, 0.65);
}

.dispatch-plan-content .title-h2 {
  margin: 0;
  font-size: 1.2rem;
  letter-spacing: 0.03em;
  text-transform: uppercase;
  color: #ffffff;
}

.dispatch-plan-content .title-p {
  margin: 6px 0 0;
  font-size: 0.9rem;
  line-height: 1.5;
  color: rgba(189, 189, 189, 0.9);
}

.quote-viewport {
  position: relative;
  @media (min-width: 1024px) {
    flex: 1;
  }
}

.conversation-rotator {
  position: relative;
  padding-top: 4px;
  padding-right: 4px;
}

.conversation-heading {
  display: flex;
  justify-content: space-between;
  gap: 12px;
  border-bottom: 1px solid rgba(var(--color-blue-rgb), 0.25);
  padding-bottom: 8px;
  color: var(--color-blue-light);
  font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono', 'Courier New', monospace;
  font-size: 0.95rem;
  letter-spacing: 0.08em;
}

.conversation-title {
  margin: 16px 0 20px;
  color: #ffffff;
  font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono', 'Courier New', monospace;
  font-size: 1.35rem;
  letter-spacing: 0.04em;
  text-transform: uppercase;
}

.conversation-messages {
  display: flex;
  flex-direction: column;
  gap: 20px;
  list-style: none;
  margin: 0;
  padding: 0;
}

.conversation-message {
  border-left: 2px solid rgba(var(--color-blue-rgb), 0.45);
  padding-left: 16px;
}

.conversation-message-header {
  display: flex;
  justify-content: space-between;
  gap: 12px;
  color: var(--color-blue);
  font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono', 'Courier New', monospace;
  font-size: 0.95rem;
  letter-spacing: 0.06em;
}

.conversation-message-header time {
  color: rgba(189, 189, 189, 0.65);
}

.conversation-message p {
  margin: 6px 0 0;
  color: rgba(255, 255, 255, 0.9);
  font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono', 'Courier New', monospace;
  font-size: 1.15rem;
  line-height: 1.65;
}

.conversation-source {
  display: flex;
  flex-direction: column;
  gap: 4px;
  border-top: 1px solid rgba(var(--color-blue-rgb), 0.25);
  margin-top: 20px;
  padding-top: 12px;
  color: rgba(189, 189, 189, 0.62);
  font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono', 'Courier New', monospace;
  font-size: 0.78rem;
  line-height: 1.45;
}

.conversation-source a {
  color: var(--color-blue);
  text-decoration: underline;
  text-decoration-color: rgba(var(--color-blue-rgb), 0.4);
  text-underline-offset: 3px;
}

.conversation-source a:hover {
  color: var(--color-blue-light);
}

.lore-quote {
  min-height: 220px;
  padding: 8px 0 0;
}

.lore-quote-mark {
  color: rgba(var(--color-blue-rgb), 0.28);
  font-family: Georgia, serif;
  font-size: 5rem;
  line-height: 0.6;
  pointer-events: none;
  user-select: none;
}

.lore-quote-text {
  margin: 18px 0 24px;
  color: #ffffff;
  font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono', 'Courier New', monospace;
  font-size: 1.25rem;
  font-style: italic;
  line-height: 1.65;
}

.lore-quote-meta {
  display: flex;
  flex-direction: column;
  gap: 5px;
  border-top: 1px solid rgba(var(--color-blue-rgb), 0.25);
  padding-top: 14px;
  color: rgba(189, 189, 189, 0.78);
  font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono', 'Courier New', monospace;
  font-size: 0.95rem;
  line-height: 1.45;
}

.lore-quote-meta strong {
  color: var(--color-blue);
  font-size: 1rem;
}

.lore-quote-meta time {
  color: rgba(189, 189, 189, 0.6);
}

.quote-nav {
  display: flex;
  gap: 8px;
  z-index: 3;

  @media (max-width: 479px) {
    position: static;
    margin-bottom: 12px;
    justify-content: flex-end;
  }

  @media (min-width: 480px) {
    position: absolute;
    top: 24px;
    right: 24px;
  }
}

.quote-nav-btn {
  width: 44px;
  height: 44px;
  border-radius: 999px;
  border: 1px solid rgba(var(--color-blue-rgb), 0.45);
  background-color: #10151f;
  color: var(--color-blue-light);
  font-size: 1.4rem;
  line-height: 1;
  cursor: pointer;
  display: inline-flex;
  align-items: center;
  justify-content: center;
  transition: all 0.2s ease;

  &:hover {
    background-color: rgba(var(--color-blue-rgb), 0.15);
    border-color: var(--color-blue-light);
    color: #ffffff;
  }
}

/* Communication transition effects */
.quote-fade-enter-active,
.quote-fade-leave-active {
  transition: opacity 0.5s ease-in-out;
}

.quote-fade-leave-active {
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
}

.quote-fade-enter-from,
.quote-fade-leave-to {
  opacity: 0;
}

// Support / QR Section
.support-wrap {
  text-align: center;
  max-width: 600px;
  margin: 0 auto;
  display: flex;
  flex-direction: column;
  gap: 8px;
}

.qr-grid {
  display: flex;
  flex-direction: column;
  gap: 24px;
  max-width: 640px;
  margin: 24px auto 0;
  width: 100%;

  @media (min-width: 600px) {
    flex-direction: row;
  }
}

.qr-card {
  flex: 1;
  background-color: #10151f;
  border: 1px solid #272727;
  padding: 24px;
  border-radius: 16px;
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 24px;
  box-shadow: 0 10px 30px rgba(0, 0, 0, 0.3);

  .qr-title {
    font-size: 1.4rem;
    font-weight: 800;
    text-transform: uppercase;
    color: #ffffff;
    margin: 0;
  }

  .qr-image-box {
    width: 192px;
    height: 192px;
    background-color: #0c1016;
    border: 1px solid #272727;
    border-radius: 12px;
    padding: 16px;
    display: flex;
    align-items: center;
    justify-content: center;
    transition: transform 0.3s;

    &:hover {
      transform: scale(1.05);
    }

    img {
      width: 100%;
      height: 100%;
      object-fit: contain;
    }
  }

  .qr-action-wrap {
    display: flex;
    flex-direction: column;
    gap: 8px;
    width: 100%;
    align-items: center;
  }

  .qr-btn {
    display: inline-block;
    color: #ffffff;
    font-weight: 700;
    font-size: 1.1rem;
    text-transform: uppercase;
    letter-spacing: 0.05em;
    padding: 8px 24px;
    border-radius: 20px;
    text-decoration: none;
    transition: background-color 0.2s;

    &.blue {
      background-color: var(--color-blue);
      &:hover {
        background-color: var(--color-blue-light);
      }
    }

    &.dark {
      background-color: #272727;
      &:hover {
        background-color: #1e1e1e;
      }
    }
  }

  .qr-domain {
    font-size: 1.1rem;
    color: #616161;
  }
}

/* Share Button */
.quote-nav-btn.share-btn {
  width: auto;
  min-width: 68px;
  padding: 0 12px;
  font-size: 0.85rem;
  font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono', 'Courier New', monospace;
  font-weight: bold;
}

/* Helper Utilities */
.font-mono {
  font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono', 'Courier New', monospace;
}
.text-cyan {
  color: var(--color-blue-light);
}
.text-gray {
  color: #888888;
}

/* Decryption Status Meter */
.decryption-meter-card {
  background-color: #10151f;
  border: 1px solid #272727;
  padding: 20px;
  border-radius: 16px;
  margin-top: 16px;
  display: flex;
  flex-direction: column;
  gap: 12px;
  box-shadow: 0 8px 24px rgba(0, 0, 0, 0.4);

  .meter-header {
    display: flex;
    justify-content: space-between;
    align-items: center;
    font-size: 0.85rem;
    letter-spacing: 0.05em;
  }

  .meter-title {
    color: #888888;
  }

  .meter-percentage {
    color: var(--color-blue-light);
    font-weight: bold;
  }

  .meter-bar-container {
    height: 6px;
    background-color: #0c1016;
    border-radius: 3px;
    overflow: hidden;
    border: 1px solid #1e1e1e;
  }

  .meter-bar-fill {
    height: 100%;
    background: linear-gradient(90deg, var(--color-blue), var(--color-blue-light));
    border-radius: 3px;
    box-shadow: 0 0 8px rgba(var(--color-blue-rgb), 0.5);
  }

  .meter-details {
    font-size: 0.75rem;
    color: #616161;
    margin: 0;
  }
}

/* Community & Conversion Section */
.community-console-grid {
  display: flex;
  flex-direction: column;
  gap: 24px;
  max-width: 900px;
  margin: 32px auto 0;
  width: 100%;

  @media (min-width: 768px) {
    flex-direction: row;
  }
}

.terminal-console-card,
.discord-invite-card {
  flex: 1;
  background-color: #10151f;
  border: 1px solid #272727;
  border-radius: 16px;
  box-shadow: 0 10px 30px rgba(0, 0, 0, 0.4);
  overflow: hidden;
}

/* Terminal Console Styling */
.terminal-console-card {
  display: flex;
  flex-direction: column;

  .console-header {
    background-color: #0c1016;
    border-bottom: 1px solid #272727;
    padding: 6px 12px;
    display: flex;
    align-items: center;
    justify-content: space-between;
  }

  .gnome-window-controls {
    display: flex;
    gap: 6px;
    align-items: center;
  }

  .gnome-control-btn {
    background: transparent;
    border: none;
    color: #5d5d5d;
    width: 24px;
    height: 24px;
    border-radius: 50%;
    display: flex;
    align-items: center;
    justify-content: center;
    cursor: pointer;
    transition: all 0.2s ease;
    padding: 0;

    &:hover {
      background-color: rgba(255, 255, 255, 0.08);
      color: #eeeeee;
    }

    &.close:hover {
      background-color: #e81123;
      color: #ffffff;
    }
  }

  .console-title {
    font-size: 0.8rem;
    color: #888888;
    text-align: left;
    flex-grow: 1;
  }

  .console-body {
    padding: 20px;
    display: flex;
    flex-direction: column;
    gap: 10px;
    flex-grow: 1;
  }

  .console-text {
    font-size: 0.9rem;
    margin: 0;
    line-height: 1.4;
  }

  .console-form {
    display: flex;
    align-items: center;
    gap: 8px;
    margin-top: 10px;
    background-color: #0c1016;
    border: 1px solid #272727;
    border-radius: 8px;
    padding: 6px 12px;

    &:focus-within {
      border-color: var(--color-blue);
      box-shadow: 0 0 8px rgba(var(--color-blue-rgb), 0.25);
    }
  }

  .console-prompt {
    color: var(--color-blue);
    font-weight: bold;
    user-select: none;
  }

  .console-input {
    flex-grow: 1;
    background: transparent;
    border: none;
    outline: none;
    color: #ffffff;
    font-size: 0.9rem;
    width: 100%;

    &::placeholder {
      color: #424242;
    }
  }

  .console-submit-btn {
    background: transparent;
    border: none;
    color: var(--color-blue-light);
    font-weight: bold;
    cursor: pointer;
    font-size: 0.85rem;
    padding: 4px 8px;
    border-radius: 4px;
    transition: all 0.2s ease;

    &:hover {
      background-color: rgba(var(--color-blue-rgb), 0.15);
      color: #ffffff;
    }

    &:disabled {
      opacity: 0.5;
      cursor: not-allowed;
    }
  }

  .console-feedback {
    font-size: 0.85rem;
    color: var(--color-blue-light);
    margin-top: 6px;

    &.success {
      color: #27c93f;
    }
  }
}

/* Discord Invite Node Styling */
.discord-invite-card {
  padding: 24px;
  display: flex;
  flex-direction: column;
  justify-content: space-between;
  gap: 16px;

  .discord-title {
    font-size: 1.1rem;
    font-weight: bold;
    color: var(--color-blue-light);
    margin: 0;
  }

  .discord-desc {
    font-size: 0.95rem;
    color: #bdbdbd;
    line-height: 1.5;
    margin: 0;
  }

  .discord-action-wrap {
    display: flex;
    flex-direction: column;
    gap: 8px;
    margin-top: auto;
  }

  .discord-btn {
    display: block;
    text-align: center;
    background: linear-gradient(135deg, #5865f2, #4752c4);
    color: #ffffff;
    font-weight: 700;
    font-size: 1rem;
    text-transform: uppercase;
    letter-spacing: 0.05em;
    padding: 12px 24px;
    border-radius: 8px;
    text-decoration: none;
    transition: all 0.2s ease;
    box-shadow: 0 4px 12px rgba(88, 101, 242, 0.3);

    &:hover {
      background: linear-gradient(135deg, #6c79ff, #5865f2);
      box-shadow: 0 6px 16px rgba(88, 101, 242, 0.4);
      transform: translateY(-1px);
    }
  }

  .discord-coords {
    font-size: 0.75rem;
    color: #616161;
    text-align: center;
  }
}

/* Support Sub-footer Links */
.support-links {
  display: flex;
  justify-content: center;
  align-items: center;
  gap: 16px;
  margin-top: 32px;
  font-size: 0.9rem;

  a {
    color: #888888;
    text-decoration: none;
    transition: color 0.2s ease;

    &:hover {
      color: var(--color-blue-light);
    }
  }

  .separator {
    color: #424242;
    user-select: none;
  }
}
</style>
