<!--
README: Bluefin Wolves Teaser Landing Page Component
===================================================
- Page Path: projectbluefin.io/wolves
- Comic Content: Delegated to WolvesComicReader.vue. PDF URL is managed
  by the component itself (BASE_URL + color-with-bluefin.pdf).
- Quotes: Sourced from `src/data/bazzite-quotes.json` with fields
  `quote`, `attribution`, optional `context`, and optional `date`.
  Real approved Discord quotes should replace placeholder lorem ipsum values in that file.
- Donate QR Code: Generated by `scripts/generate-qrs.js` and currently points to `#`.
  Replace `donateUrl` in `scripts/generate-qrs.js` and re-run the script when the real URL is ready.
- Playlist ID in use: `PLA78oiE-RGAE` ("Bluefin: Seven Days to the Wolves" on YouTube).
- Playback approach: click-to-start in-page YouTube playlist player + visible YouTube Music deep link.
  We do not attempt auth-state detection because YouTube sign-in/Premium status cannot be reliably verified in-browser.
- Future Spotify support: add a Spotify URI/provider adapter in `src/data/wolves-playlist.json`
  and `WolvesSoundtrack.vue` without redesigning page layout.
-->
<script setup lang="ts">
import type { WolvesSoundtrackManifest } from './data/wolves-soundtrack'
import { computed, onBeforeUnmount, onMounted, ref, watch } from 'vue'
import TopNavbar from './components/TopNavbar.vue'
import WolvesComicReader from './components/wolves/WolvesComicReader.vue'
import WolvesLoreColumn from './components/wolves/WolvesLoreColumn.vue'
import WolvesQrCodes from './components/wolves/WolvesQrCodes.vue'
import WolvesSoundtrack from './components/wolves/WolvesSoundtrack.vue'
import { getNarrativeSlotForTime } from './data/wolves-narrative-timeline'
import { loadWolvesSoundtrack } from './data/wolves-soundtrack'
import { wolvesRelease } from './data/wolves-story'
import { getWolvesThesisState } from './data/wolves-thesis-sequence'

const isPlaying = ref(false)
const isEquinoxActive = ref(false)
const equinoxTrackTitle = ref('')
const equinoxTrackArtist = ref('')
const soundtrackManifest = ref<WolvesSoundtrackManifest | null>(null)

// Background Wallpaper State
const playlistCurrentTime = ref(0)
const playlistDuration = ref(0)
const playlistTrackIndex = ref(0)
const presentationSnapshot = ref<{ trackIndex: number, currentTime: number } | null>(null)
const presentationTrackIndex = computed(() => presentationSnapshot.value?.trackIndex ?? playlistTrackIndex.value)
const presentationCurrentTime = computed(() => presentationSnapshot.value?.currentTime ?? playlistCurrentTime.value)
const isSoundtrackActive = ref(false)
const isGalleryPresentation = computed(() => presentationTrackIndex.value > 0)
const currentNarrativeSlot = computed(() =>
  getNarrativeSlotForTime(presentationTrackIndex.value === 0 ? presentationCurrentTime.value : Number.POSITIVE_INFINITY),
)
const thesisState = computed(() =>
  presentationTrackIndex.value === 0 ? getWolvesThesisState(presentationCurrentTime.value) : getWolvesThesisState(-1),
)

const activeNarrativeArtifact = computed(() =>
  wolvesRelease.artifacts.find(artifact => artifact.id === currentNarrativeSlot.value.artifactId),
)

const activeChapter = computed(() =>
  wolvesRelease.chapters.find(chapter => chapter.id === activeNarrativeArtifact.value?.chapterId),
)

const isImmersive = ref(false)
const EQUINOX_ENTER_DURATION = 1500
let equinoxTimeout: ReturnType<typeof setTimeout> | null = null
let presentationTimeout: ReturnType<typeof setTimeout> | null = null
let equinoxTransitionId = 0

watch(playlistTrackIndex, (newVal) => {
  if (!isSoundtrackActive.value || !isImmersive.value) {
    return
  }

  const transitionId = ++equinoxTransitionId

  if (soundtrackManifest.value && soundtrackManifest.value.tracks[newVal]) {
    const track = soundtrackManifest.value.tracks[newVal]
    equinoxTrackTitle.value = track.title
    equinoxTrackArtist.value = track.artist
  }
  else {
    equinoxTrackTitle.value = newVal === 0 ? '7 Days to the Wolves' : `Track ${newVal + 1}`
    equinoxTrackArtist.value = 'Nightwish'
  }

  isEquinoxActive.value = true

  if (equinoxTimeout) {
    clearTimeout(equinoxTimeout)
  }
  if (presentationTimeout) {
    clearTimeout(presentationTimeout)
  }

  presentationTimeout = setTimeout(() => {
    if (transitionId === equinoxTransitionId) {
      presentationSnapshot.value = null
      presentationTimeout = null
    }
  }, EQUINOX_ENTER_DURATION)

  equinoxTimeout = setTimeout(() => {
    if (transitionId === equinoxTransitionId) {
      isEquinoxActive.value = false
      equinoxTimeout = null
    }
  }, 6000)
})

function handleProgress(data: { currentTime: number, duration: number, playlistIndex: number }) {
  if (isSoundtrackActive.value && data.playlistIndex !== playlistTrackIndex.value) {
    presentationSnapshot.value = {
      trackIndex: presentationTrackIndex.value,
      currentTime: presentationCurrentTime.value,
    }
  }
  playlistCurrentTime.value = data.currentTime
  playlistDuration.value = data.duration
  playlistTrackIndex.value = data.playlistIndex
  isSoundtrackActive.value = true
}

const totalProgress = computed(() => {
  if (!isSoundtrackActive.value || playlistDuration.value <= 0) {
    return 0
  }
  const trackProgress = playlistCurrentTime.value / playlistDuration.value
  return Math.min(1, Math.max(0, (playlistTrackIndex.value + trackProgress) / 7))
})

const wallpaperNightOpacity = computed(() => {
  if (thesisState.value.dayPulse || !isSoundtrackActive.value) {
    return 0
  }
  const wallpaperIndexFloat = totalProgress.value * 12 + 6
  return Math.sin((wallpaperIndexFloat - Math.floor(wallpaperIndexFloat)) * Math.PI)
})

const currentPairIndex = computed(() => {
  if (!isSoundtrackActive.value) {
    return 6 // Start with July (index 6, Month 7) by default
  }
  const wallpaperIndexFloat = totalProgress.value * 12 + 6
  return Math.floor(wallpaperIndexFloat) % 12
})

const activeMonth = ref(6)
const previousMonth = ref<number | null>(null)
const isTransitioning = ref(false)

watch(currentPairIndex, (newVal, oldVal) => {
  if (oldVal !== undefined && newVal !== oldVal) {
    previousMonth.value = oldVal
    activeMonth.value = newVal
    isTransitioning.value = true
    setTimeout(() => {
      previousMonth.value = null
      isTransitioning.value = false
    }, 1500)
  }
  else {
    activeMonth.value = newVal
  }
}, { immediate: true })

function getDayWallpaperUrl(monthIndex: number) {
  const pairStr = String(monthIndex + 1).padStart(2, '0')
  return `url('${import.meta.env.BASE_URL}img/wallpapers/bluefin-${pairStr}-day.webp')`
}

function getNightWallpaperUrl(monthIndex: number) {
  const pairStr = String(monthIndex + 1).padStart(2, '0')
  return `url('${import.meta.env.BASE_URL}img/wallpapers/bluefin-${pairStr}-night.webp')`
}

function enterImmersiveExperience() {
  const transition = () => {
    isImmersive.value = true
    isPlaying.value = true
  }

  const documentWithTransition = document as Document & {
    startViewTransition?: (cb: () => void) => void
  }

  if (documentWithTransition.startViewTransition) {
    documentWithTransition.startViewTransition(transition)
  }
  else {
    transition()
  }
}

function exitImmersiveExperience() {
  const transition = () => {
    isImmersive.value = false
    isEquinoxActive.value = false
    equinoxTransitionId++
    if (equinoxTimeout) {
      clearTimeout(equinoxTimeout)
      equinoxTimeout = null
    }
    if (presentationTimeout) {
      clearTimeout(presentationTimeout)
      presentationTimeout = null
    }
    presentationSnapshot.value = null
    playlistCurrentTime.value = 0
    playlistDuration.value = 0
    playlistTrackIndex.value = 0
  }

  const documentWithTransition = document as Document & {
    startViewTransition?: (cb: () => void) => void
  }

  if (documentWithTransition.startViewTransition) {
    documentWithTransition.startViewTransition(transition)
  }
  else {
    transition()
  }
}

function handleKeyDown(event: KeyboardEvent) {
  if (event.key === 'Escape' && isImmersive.value) {
    exitImmersiveExperience()
  }
}

onMounted(async () => {
  window.addEventListener('keydown', handleKeyDown)
  try {
    soundtrackManifest.value = await loadWolvesSoundtrack()
  }
  catch (err) {
    console.error('Failed to load wolves soundtrack manifest:', err)
  }
})

onBeforeUnmount(() => {
  window.removeEventListener('keydown', handleKeyDown)
  if (equinoxTimeout) {
    clearTimeout(equinoxTimeout)
  }
  if (presentationTimeout) {
    clearTimeout(presentationTimeout)
  }
})
</script>

<template>
  <div class="wolves-teaser-page">
    <!-- Dynamic Wallpaper Background Layers -->
    <div class="wallpaper-container">
      <!-- Previous Month Buffer (fading out) -->
      <div v-if="previousMonth !== null" class="wallpaper-buffer-layer fading-out">
        <div class="wallpaper-layer day-layer" :style="{ backgroundImage: getDayWallpaperUrl(previousMonth) }" />
        <div class="wallpaper-layer night-layer" :style="{ backgroundImage: getNightWallpaperUrl(previousMonth), opacity: wallpaperNightOpacity }" />
      </div>

      <!-- Active Month Buffer (fading in) -->
      <div class="wallpaper-buffer-layer" :class="{ 'is-transitioning': isTransitioning }">
        <div class="wallpaper-layer day-layer" :style="{ backgroundImage: getDayWallpaperUrl(activeMonth) }" />
        <div class="wallpaper-layer night-layer" :style="{ backgroundImage: getNightWallpaperUrl(activeMonth), opacity: wallpaperNightOpacity }" />
      </div>
    </div>

    <!-- Top Global Navigation Bar -->
    <TopNavbar v-if="!isImmersive" />

    <!-- Main Outer Container -->
    <div v-if="!isImmersive" class="wolves-layout">
      <!-- SECTION 1: HERO SECTION -->
      <header class="wolves-hero">
        <div class="hero-text">
          <!-- Aggressive display typography with heavy scale -->
          <h1 class="hero-title">
            Seven Days to the <span class="accent">Wolves</span>
          </h1>
          <p class="hero-description">
            In the distant future, open source maintainers are not only sought after, they are hunted. Enslaved by the very machines they created, betrayed by the societies they swore to protect. They fight alone.

            <br><br>Our Childhood's End, is their beginning.

            <br><br>A fundraising effort to immortalize contributors in legend. Issue sponsorships available.
          </p>

          <div class="experience-cta-wrap">
            <button class="experience-cta-btn font-mono" @click="enterImmersiveExperience">
              ▶ JOIN THE EVOLUTION
            </button>
            <div class="experience-cta-sub font-mono">
              RECOMMENDED: HEADPHONES ON // VOLUME UP
            </div>
          </div>

          <div class="hero-footnote">
            Coming 2027
          </div>
        </div>
      </header>

      <section class="wolves-page-qr comic-reader-section">
        <WolvesQrCodes />
      </section>
    </div>

    <!-- Immersive Fullscreen Theater Experience -->
    <div v-else class="immersive-layout">
      <!-- TOP STATUS BAR HUD -->
      <header class="immersive-hud-header" :class="{ 'is-thesis-active': thesisState.active }">
        <div class="hud-left font-mono">
          <span class="hud-indicator-dot animate-pulse-fast" />
          {{ thesisState.hudLabel || 'kubectl get pods -n wolves --selector=app=seven-days-to-the-wolves --watch' }}
        </div>
        <button class="hud-exit-btn font-mono" @click="exitImmersiveExperience">
          [ EXIT EXPERIENCE ]
        </button>
      </header>

      <!-- MIDDLE CONTENT AREA (WIDESCREEN SPLIT 2fr 1fr) -->
      <div
        class="immersive-content-grid"
        :data-presentation="isGalleryPresentation ? 'centered-gallery' : 'narrative-split'"
      >
        <div class="immersive-col-left">
          <WolvesComicReader
            :track-index="isSoundtrackActive ? presentationTrackIndex : undefined"
            :playlist-current-time="presentationCurrentTime"
          />
        </div>

        <div v-if="!isGalleryPresentation" class="immersive-col-right">
          <WolvesLoreColumn
            :artifact-id="currentNarrativeSlot.artifactId"
            :duration="currentNarrativeSlot.endTime - currentNarrativeSlot.startTime"
            :warning="thesisState.warning"
          />
        </div>

        <div v-if="thesisState.active" class="thesis-overlay font-mono" :class="`is-${thesisState.mode}`">
          <p v-if="thesisState.subtitle">
            {{ thesisState.subtitle }}
          </p>
          <h1 v-if="thesisState.text">
            {{ thesisState.text }}
          </h1>
          <span v-if="thesisState.mode === 'corruption' || thesisState.mode === 'growing-corruption'">!&lt;&gt;-_\\/[]{}—=+*^?#________X01</span>
        </div>
      </div>

      <!-- EQUINOX OVERLAY -->
      <transition name="equinox-fade">
        <div v-if="isEquinoxActive" class="equinox-overlay">
          <div class="equinox-title-wrap font-mono">
            <div class="equinox-label text-cyan animate-pulse-fast">
              // EQUINOX SHIFT DETECTED //
            </div>
            <h1 class="equinox-track-title">
              {{ equinoxTrackTitle }}
            </h1>
            <p class="equinox-track-artist text-gray">
              {{ equinoxTrackArtist }}
            </p>
          </div>
        </div>
      </transition>

      <!-- BOTTOM CONTROLS HUD -->
      <footer class="immersive-hud-footer">
        <!-- Soundtrack Dock -->
        <div class="immersive-soundtrack-dock">
          <WolvesSoundtrack
            v-model:playing="isPlaying"
            :chapter="activeChapter"
            @progress="handleProgress"
          />
        </div>

        <!-- Telemetry -->
        <div class="hud-right-telemetry font-mono">
          <div class="decryption-mini-meter">
            <div class="meter-header-mini">
              <span>DEPLOYMENT: wolves-decryption-engine-7</span>
              <span class="text-cyan">7%</span>
            </div>
            <div class="meter-bar-mini">
              <div class="meter-fill-mini" />
            </div>
          </div>
          <div class="hud-telemetry-coords">
            CLUSTER: k3s-exo-1.production // HOST: ghost.local
          </div>
        </div>
      </footer>
    </div>
  </div>
</template>

<style scoped lang="scss">
.wallpaper-container {
  position: fixed;
  top: 0;
  left: 0;
  width: 100vw;
  height: 100vh;
  overflow: hidden;
  pointer-events: none;
  z-index: 0;
}

.wallpaper-buffer-layer {
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  opacity: 1;
  pointer-events: none;
  will-change: opacity;
  transform: translateZ(0);

  &.fading-out {
    animation: fadeOutBuffer 1.5s linear forwards;
    z-index: 1;
  }

  &.is-transitioning {
    z-index: 2;
    animation: fadeInBuffer 1.5s linear forwards;
  }
}

@keyframes fadeInBuffer {
  from {
    opacity: 0;
  }
  to {
    opacity: 1;
  }
}

@keyframes fadeOutBuffer {
  from {
    opacity: 1;
  }
  to {
    opacity: 0;
  }
}

.wallpaper-layer {
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  background-size: cover;
  background-position: center;
  background-repeat: no-repeat;
  pointer-events: none;
  transform: translateZ(0);
}

.day-layer {
  z-index: 1;
}

.night-layer {
  z-index: 2;
  transition: opacity 0.5s linear;
  will-change: opacity;
  transform: translateZ(0);
}

.wolves-teaser-page {
  background-color: #0c1016;
  min-height: 100vh;
  position: relative;
  // Firefox can break sticky descendants when an ancestor creates a scrolling
  // container via overflow. `clip` prevents horizontal bleed without that side
  // effect.
  overflow-x: clip;
  box-sizing: border-box;
}

.wolves-layout {
  position: relative;
  z-index: 3;
  max-width: 1280px;
  margin: 0 auto;
  padding: 12px 24px 40px;
  display: flex;
  flex-direction: column;
  gap: 24px;
}

.wolves-page-qr {
  margin-top: 8px;
}

// Two-column desktop grid: Comic Reader (left) + pinned Soundtrack Widget /
// Bazzite Dispatch sidebar (right). Falls back to a vertical stack below
// 1024px.
.content-grid {
  display: flex;
  flex-direction: column;
  gap: 16px;
  width: 100%;

  @media (min-width: 1024px) {
    display: grid;
    grid-template-columns: 2fr 1fr;
    align-items: stretch;
    gap: 16px;
  }
}

.col-left {
  min-width: 0;
  display: flex;
  flex-direction: column;
  gap: 16px;
  height: 100%;

  // Left-align the comic reader within its column instead of the
  // page-wide auto-centering used when the reader is the sole column.
  :deep(.comic-viewport),
  :deep(.scroll-comic-layout),
  :deep(.reader-controls),
  :deep(.sidebar-soundtrack-card) {
    margin-left: 0;
    margin-right: 0;
    max-width: 100%;
    width: 100%;
  }
}

.col-right {
  min-width: 0;
  display: flex;
  flex-direction: column;
  gap: 16px;

  @media (min-width: 1024px) {
    height: 100%;
  }
}

// Persistent Floating Soundtrack Widget (markup moved to WolvesSoundtrack component)
// Mobile: reserve space at the bottom of the page for the fixed player bar,
// but only while the bar is actually visible (class toggled by WolvesSoundtrack).
:global(.wolves-player-active) .wolves-layout {
  @media (max-width: 767px) {
    padding-bottom: calc(88px + env(safe-area-inset-bottom));
  }
}

// Hero Section
.wolves-hero {
  display: flex;
  flex-direction: column;
  gap: 12px;
  padding: 12px 0 10px;

  .hero-text {
    text-align: center;
    background-color: rgba(16, 21, 31, 0.75);
    border: 1px solid rgba(var(--color-blue-rgb), 0.2);
    border-radius: 16px;
    padding: 32px;
    box-shadow: 0 10px 30px rgba(0, 0, 0, 0.5);
    backdrop-filter: blur(2px);
    max-width: 800px;
    margin: 0 auto;

    @media (min-width: 768px) {
      text-align: left;
      padding: 48px;
    }
  }

  .hero-title {
    font-size: clamp(2.8rem, 4.8vw, 4.2rem);
    font-weight: 800;
    letter-spacing: -0.03em;
    line-height: 1.1;
    text-transform: uppercase;
    margin-bottom: 12px;

    @media (min-width: 768px) {
      font-size: clamp(3.8rem, 5.8vw, 5.2rem);
    }

    .accent {
      color: var(--color-blue);
    }
  }

  .hero-description {
    font-size: 1.3rem;
    line-height: 1.6;
    color: #bdbdbd;
    margin-bottom: 12px;
    max-width: 600px;
  }

  .hero-footnote {
    font-size: 1rem;
    color: rgba(189, 189, 189, 0.6);
    font-style: italic;
  }
}

@keyframes pulse {
  0% {
    transform: scale(1);
    opacity: 0.8;
  }
  50% {
    transform: scale(1.1);
    opacity: 1;
  }
  100% {
    transform: scale(1);
    opacity: 0.8;
  }
}

.dispatch-quote-section {
  @media (min-width: 1024px) {
    flex: 1;
    display: flex;
    flex-direction: column;
  }
}

// Intercepted communications section
.dispatch-quote-card {
  background-color: #10151f;
  border: 1px solid #272727;
  padding: 16px;
  border-radius: 16px;
  display: flex;
  flex-direction: column;
  gap: 16px;
  position: relative;
  width: 100%;
  box-shadow: 0 10px 25px rgba(0, 0, 0, 0.3);
  transition:
    border-color 0.3s,
    box-shadow 0.3s;

  @media (min-width: 1024px) {
    flex: 1;
  }

  &:hover {
    border-color: rgba(var(--color-blue-rgb), 0.4);
    box-shadow: 0 10px 25px rgba(0, 0, 0, 0.3);
  }
}

.dispatch-plan-content {
  font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono', 'Courier New', monospace;
  background: linear-gradient(180deg, rgba(16, 21, 31, 0.98) 0%, rgba(12, 16, 22, 0.98) 100%);
  border: 1px solid rgba(var(--color-blue-rgb), 0.22);
  border-radius: 10px;
  padding: 12px 14px;
  box-shadow: inset 0 1px 0 rgba(255, 255, 255, 0.05);

  @media (min-width: 480px) {
    padding-right: 192px;
  }
}

.dispatch-plan-command {
  margin: 0 0 6px;
  font-size: 0.86rem;
  color: rgba(189, 189, 189, 0.65);
}

.dispatch-plan-content .title-h2 {
  margin: 0;
  font-size: 1.2rem;
  letter-spacing: 0.03em;
  text-transform: uppercase;
  color: #ffffff;
}

.dispatch-plan-content .title-p {
  margin: 6px 0 0;
  font-size: 0.9rem;
  line-height: 1.5;
  color: rgba(189, 189, 189, 0.9);
}

.quote-viewport {
  position: relative;
  @media (min-width: 1024px) {
    flex: 1;
  }
}

.conversation-rotator {
  position: relative;
  padding-top: 4px;
  padding-right: 4px;
}

.conversation-heading {
  display: flex;
  justify-content: space-between;
  gap: 12px;
  border-bottom: 1px solid rgba(var(--color-blue-rgb), 0.25);
  padding-bottom: 8px;
  color: var(--color-blue-light);
  font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono', 'Courier New', monospace;
  font-size: 0.95rem;
  letter-spacing: 0.08em;
}

.conversation-title {
  margin: 16px 0 20px;
  color: #ffffff;
  font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono', 'Courier New', monospace;
  font-size: 1.35rem;
  letter-spacing: 0.04em;
  text-transform: uppercase;
}

.conversation-messages {
  display: flex;
  flex-direction: column;
  gap: 20px;
  list-style: none;
  margin: 0;
  padding: 0;
}

.conversation-message {
  border-left: 2px solid rgba(var(--color-blue-rgb), 0.45);
  padding-left: 16px;
}

.conversation-message-header {
  display: flex;
  justify-content: space-between;
  gap: 12px;
  color: var(--color-blue);
  font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono', 'Courier New', monospace;
  font-size: 0.95rem;
  letter-spacing: 0.06em;
}

.conversation-message-header time {
  color: rgba(189, 189, 189, 0.65);
}

.conversation-message p {
  margin: 6px 0 0;
  color: rgba(255, 255, 255, 0.9);
  font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono', 'Courier New', monospace;
  font-size: 1.15rem;
  line-height: 1.65;
}

.conversation-source {
  display: flex;
  flex-direction: column;
  gap: 4px;
  border-top: 1px solid rgba(var(--color-blue-rgb), 0.25);
  margin-top: 20px;
  padding-top: 12px;
  color: rgba(189, 189, 189, 0.62);
  font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono', 'Courier New', monospace;
  font-size: 0.78rem;
  line-height: 1.45;
}

.conversation-source a {
  color: var(--color-blue);
  text-decoration: underline;
  text-decoration-color: rgba(var(--color-blue-rgb), 0.4);
  text-underline-offset: 3px;
}

.conversation-source a:hover {
  color: var(--color-blue-light);
}

.lore-quote {
  min-height: 220px;
  padding: 8px 0 0;
}

.lore-quote-mark {
  color: rgba(var(--color-blue-rgb), 0.28);
  font-family: Georgia, serif;
  font-size: 5rem;
  line-height: 0.6;
  pointer-events: none;
  user-select: none;
}

.lore-quote-text {
  margin: 18px 0 24px;
  color: #ffffff;
  font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono', 'Courier New', monospace;
  font-size: 1.25rem;
  font-style: italic;
  line-height: 1.65;
}

.lore-quote-meta {
  display: flex;
  flex-direction: column;
  gap: 5px;
  border-top: 1px solid rgba(var(--color-blue-rgb), 0.25);
  padding-top: 14px;
  color: rgba(189, 189, 189, 0.78);
  font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono', 'Courier New', monospace;
  font-size: 0.95rem;
  line-height: 1.45;
}

.lore-quote-meta strong {
  color: var(--color-blue);
  font-size: 1rem;
}

.lore-quote-meta time {
  color: rgba(189, 189, 189, 0.6);
}

.quote-nav {
  display: flex;
  gap: 8px;
  z-index: 3;

  @media (max-width: 479px) {
    position: static;
    margin-bottom: 12px;
    justify-content: flex-end;
  }

  @media (min-width: 480px) {
    position: absolute;
    top: 24px;
    right: 24px;
  }
}

.quote-nav-btn {
  width: 44px;
  height: 44px;
  border-radius: 999px;
  border: 1px solid rgba(var(--color-blue-rgb), 0.45);
  background-color: #10151f;
  color: var(--color-blue-light);
  font-size: 1.4rem;
  line-height: 1;
  cursor: pointer;
  display: inline-flex;
  align-items: center;
  justify-content: center;
  transition: all 0.2s ease;

  &:hover {
    background-color: rgba(var(--color-blue-rgb), 0.15);
    border-color: var(--color-blue-light);
    color: #ffffff;
  }
}

/* Communication transition effects */
.quote-fade-enter-active,
.quote-fade-leave-active {
  transition: opacity 0.5s ease-in-out;
}

.quote-fade-leave-active {
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
}

.quote-fade-enter-from,
.quote-fade-leave-to {
  opacity: 0;
}

// Support / QR Section
.support-wrap {
  text-align: center;
  max-width: 600px;
  margin: 0 auto;
  display: flex;
  flex-direction: column;
  gap: 8px;
}

.qr-grid {
  display: flex;
  flex-direction: column;
  gap: 24px;
  max-width: 640px;
  margin: 24px auto 0;
  width: 100%;

  @media (min-width: 600px) {
    flex-direction: row;
  }
}

.qr-card {
  flex: 1;
  background-color: #10151f;
  border: 1px solid #272727;
  padding: 24px;
  border-radius: 16px;
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 24px;
  box-shadow: 0 10px 30px rgba(0, 0, 0, 0.3);

  .qr-title {
    font-size: 1.4rem;
    font-weight: 800;
    text-transform: uppercase;
    color: #ffffff;
    margin: 0;
  }

  .qr-image-box {
    width: 192px;
    height: 192px;
    background-color: #0c1016;
    border: 1px solid #272727;
    border-radius: 12px;
    padding: 16px;
    display: flex;
    align-items: center;
    justify-content: center;
    transition: transform 0.3s;

    &:hover {
      transform: scale(1.05);
    }

    img {
      width: 100%;
      height: 100%;
      object-fit: contain;
    }
  }

  .qr-action-wrap {
    display: flex;
    flex-direction: column;
    gap: 8px;
    width: 100%;
    align-items: center;
  }

  .qr-btn {
    display: inline-block;
    color: #ffffff;
    font-weight: 700;
    font-size: 1.1rem;
    text-transform: uppercase;
    letter-spacing: 0.05em;
    padding: 8px 24px;
    border-radius: 20px;
    text-decoration: none;
    transition: background-color 0.2s;

    &.blue {
      background-color: var(--color-blue);
      &:hover {
        background-color: var(--color-blue-light);
      }
    }

    &.dark {
      background-color: #272727;
      &:hover {
        background-color: #1e1e1e;
      }
    }
  }

  .qr-domain {
    font-size: 1.1rem;
    color: #616161;
  }
}

/* Share Button */
.quote-nav-btn.share-btn {
  width: auto;
  min-width: 68px;
  padding: 0 12px;
  font-size: 0.85rem;
  font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono', 'Courier New', monospace;
  font-weight: bold;
}

/* Helper Utilities */
.font-mono {
  font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono', 'Courier New', monospace;
}
.text-cyan {
  color: var(--color-blue-light);
}
.text-gray {
  color: #888888;
}

/* Decryption Status Meter */
.decryption-meter-card {
  background-color: #10151f;
  border: 1px solid #272727;
  padding: 20px;
  border-radius: 16px;
  margin-top: 16px;
  display: flex;
  flex-direction: column;
  gap: 12px;
  box-shadow: 0 8px 24px rgba(0, 0, 0, 0.4);

  .meter-header {
    display: flex;
    justify-content: space-between;
    align-items: center;
    font-size: 0.85rem;
    letter-spacing: 0.05em;
  }

  .meter-title {
    color: #888888;
  }

  .meter-percentage {
    color: var(--color-blue-light);
    font-weight: bold;
  }

  .meter-bar-container {
    height: 6px;
    background-color: #0c1016;
    border-radius: 3px;
    overflow: hidden;
    border: 1px solid #1e1e1e;
  }

  .meter-bar-fill {
    height: 100%;
    background: linear-gradient(90deg, var(--color-blue), var(--color-blue-light));
    border-radius: 3px;
    box-shadow: 0 0 8px rgba(var(--color-blue-rgb), 0.5);
  }

  .meter-details {
    font-size: 0.75rem;
    color: #616161;
    margin: 0;
  }
}

/* Community & Conversion Section */
.community-console-grid {
  display: flex;
  flex-direction: column;
  gap: 24px;
  max-width: 900px;
  margin: 32px auto 0;
  width: 100%;

  @media (min-width: 768px) {
    flex-direction: row;
  }
}

.terminal-console-card,
.discord-invite-card {
  flex: 1;
  background-color: #10151f;
  border: 1px solid #272727;
  border-radius: 16px;
  box-shadow: 0 10px 30px rgba(0, 0, 0, 0.4);
  overflow: hidden;
}

/* Terminal Console Styling */
.terminal-console-card {
  display: flex;
  flex-direction: column;

  .console-header {
    background-color: #0c1016;
    border-bottom: 1px solid #272727;
    padding: 6px 12px;
    display: flex;
    align-items: center;
    justify-content: space-between;
  }

  .gnome-window-controls {
    display: flex;
    gap: 6px;
    align-items: center;
  }

  .gnome-control-btn {
    background: transparent;
    border: none;
    color: #5d5d5d;
    width: 24px;
    height: 24px;
    border-radius: 50%;
    display: flex;
    align-items: center;
    justify-content: center;
    cursor: pointer;
    transition: all 0.2s ease;
    padding: 0;

    &:hover {
      background-color: rgba(255, 255, 255, 0.08);
      color: #eeeeee;
    }

    &.close:hover {
      background-color: #e81123;
      color: #ffffff;
    }
  }

  .console-title {
    font-size: 0.8rem;
    color: #888888;
    text-align: left;
    flex-grow: 1;
  }

  .console-body {
    padding: 20px;
    display: flex;
    flex-direction: column;
    gap: 10px;
    flex-grow: 1;
  }

  .console-text {
    font-size: 0.9rem;
    margin: 0;
    line-height: 1.4;
  }

  .console-form {
    display: flex;
    align-items: center;
    gap: 8px;
    margin-top: 10px;
    background-color: #0c1016;
    border: 1px solid #272727;
    border-radius: 8px;
    padding: 6px 12px;

    &:focus-within {
      border-color: var(--color-blue);
      box-shadow: 0 0 8px rgba(var(--color-blue-rgb), 0.25);
    }
  }

  .console-prompt {
    color: var(--color-blue);
    font-weight: bold;
    user-select: none;
  }

  .console-input {
    flex-grow: 1;
    background: transparent;
    border: none;
    outline: none;
    color: #ffffff;
    font-size: 0.9rem;
    width: 100%;

    &::placeholder {
      color: #424242;
    }
  }

  .console-submit-btn {
    background: transparent;
    border: none;
    color: var(--color-blue-light);
    font-weight: bold;
    cursor: pointer;
    font-size: 0.85rem;
    padding: 4px 8px;
    border-radius: 4px;
    transition: all 0.2s ease;

    &:hover {
      background-color: rgba(var(--color-blue-rgb), 0.15);
      color: #ffffff;
    }

    &:disabled {
      opacity: 0.5;
      cursor: not-allowed;
    }
  }

  .console-feedback {
    font-size: 0.85rem;
    color: var(--color-blue-light);
    margin-top: 6px;

    &.success {
      color: #27c93f;
    }
  }
}

/* Discord Invite Node Styling */
.discord-invite-card {
  padding: 24px;
  display: flex;
  flex-direction: column;
  justify-content: space-between;
  gap: 16px;

  .discord-title {
    font-size: 1.1rem;
    font-weight: bold;
    color: var(--color-blue-light);
    margin: 0;
  }

  .discord-desc {
    font-size: 0.95rem;
    color: #bdbdbd;
    line-height: 1.5;
    margin: 0;
  }

  .discord-action-wrap {
    display: flex;
    flex-direction: column;
    gap: 8px;
    margin-top: auto;
  }

  .discord-btn {
    display: block;
    text-align: center;
    background: linear-gradient(135deg, #5865f2, #4752c4);
    color: #ffffff;
    font-weight: 700;
    font-size: 1rem;
    text-transform: uppercase;
    letter-spacing: 0.05em;
    padding: 12px 24px;
    border-radius: 8px;
    text-decoration: none;
    transition: all 0.2s ease;
    box-shadow: 0 4px 12px rgba(88, 101, 242, 0.3);

    &:hover {
      background: linear-gradient(135deg, #6c79ff, #5865f2);
      box-shadow: 0 6px 16px rgba(88, 101, 242, 0.4);
      transform: translateY(-1px);
    }
  }

  .discord-coords {
    font-size: 0.75rem;
    color: #616161;
    text-align: center;
  }
}

/* Support Sub-footer Links */
.support-links {
  display: flex;
  justify-content: center;
  align-items: center;
  gap: 16px;
  margin-top: 32px;
  font-size: 0.9rem;

  a {
    color: #888888;
    text-decoration: none;
    transition: color 0.2s ease;

    &:hover {
      color: var(--color-blue-light);
    }
  }

  .separator {
    color: #424242;
    user-select: none;
  }
}

/* Experience Entrance CTA Styling */
.experience-cta-wrap {
  margin: 16px 0 8px;
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 8px;

  @media (min-width: 768px) {
    align-items: flex-start;
  }
}

.experience-cta-btn {
  background: linear-gradient(135deg, #2563eb, #3b82f6);
  border: 1px solid rgba(147, 197, 253, 0.4);
  color: #ffffff;
  padding: 16px 32px;
  font-size: 1.65rem; /* Upgraded 50% from 1.1rem! */
  font-weight: bold;
  border-radius: 8px;
  cursor: pointer;
  transition: all 0.3s cubic-bezier(0.4, 0, 0.2, 1);
  box-shadow: 0 0 20px rgba(37, 99, 235, 0.5);
  letter-spacing: 0.05em;
  animation: pulse-glow 2.5s infinite;

  &:hover {
    background: linear-gradient(135deg, #3b82f6, #60a5fa);
    border-color: #93c5fd;
    box-shadow: 0 0 30px rgba(59, 130, 246, 0.8);
    transform: translateY(-2px) scale(1.02);
  }

  &:active {
    transform: translateY(1px) scale(0.98);
  }
}

@keyframes pulse-glow {
  0% {
    box-shadow: 0 0 15px rgba(37, 99, 235, 0.4);
  }
  50% {
    box-shadow: 0 0 30px rgba(59, 130, 246, 0.8);
  }
  100% {
    box-shadow: 0 0 15px rgba(37, 99, 235, 0.4);
  }
}

.experience-cta-sub {
  font-size: 1.2rem; /* Upgraded 50% from 0.8rem! */
  color: #888888;
  letter-spacing: 0.1em;
}

/* Immersive Experience Active State */
.wolves-teaser-page.immersive-experience-active {
  overflow: hidden;
  height: 100vh;
  width: 100vw;
}

/* Immersive Fullscreen Dashboard */
.immersive-layout {
  position: fixed;
  top: 0;
  left: 0;
  width: 100vw;
  height: 100vh;
  z-index: 100;
  background-color: rgba(12, 16, 22, 0.35);
  display: flex;
  flex-direction: column;
  box-sizing: border-box;
  overflow: hidden;
}

/* Immersive Top Header HUD */
.immersive-hud-header {
  height: 80px; /* Upgraded from 60px to fit 50% larger typography comfortably */
  border-bottom: 1px solid rgba(102, 179, 255, 0.2);
  background: rgba(16, 21, 31, 0.45);
  backdrop-filter: blur(12px);
  padding: 0 24px;
  display: flex;
  align-items: center;
  justify-content: space-between;
  flex-shrink: 0;

  &.is-thesis-active {
    border-color: #7dd3fc;
    background: rgba(8, 28, 45, 0.78);
    box-shadow: 0 0 24px rgba(125, 211, 252, 0.55);
  }

  .hud-left {
    display: flex;
    align-items: center;
    gap: 10px;
    font-size: 1.35rem; /* Upgraded 50% from 0.9rem! */
    font-weight: bold;
    color: #e2e8f0;
    letter-spacing: 0.05em;
  }

  .thesis-overlay {
    position: fixed;
    inset: 80px 0 140px;
    z-index: 30;
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    pointer-events: none;
    color: #ffffff;
    text-align: center;
    text-shadow:
      0 0 24px #7dd3fc,
      0 0 52px rgba(255, 255, 255, 0.7);

    h1 {
      margin: 0;
      font-size: clamp(2rem, 6vw, 6rem);
      font-weight: 900;
    }
    p {
      margin: 0 0 16px;
      font-size: clamp(1rem, 2vw, 2rem);
      letter-spacing: 0.15em;
    }
    span {
      font-size: clamp(1.2rem, 3vw, 3rem);
      letter-spacing: 0.12em;
    }

    &.is-welcome,
    &.is-universal-blue,
    &.is-evolve {
      h1 {
        font-size: clamp(1.5rem, 3.5vw, 3.5rem);
      }
    }
    &.is-legend {
      background: radial-gradient(circle, rgba(26, 71, 105, 0.45), transparent 65%);
    }
  }

  .hud-indicator-dot {
    width: 8px;
    height: 8px;
    border-radius: 50%;
    background-color: #27c93f;
    box-shadow: 0 0 10px #27c93f;
  }

  .hud-exit-btn {
    background: transparent;
    border: 1px solid rgba(248, 113, 113, 0.4);
    color: rgba(248, 113, 113, 0.9);
    padding: 8px 16px;
    font-size: 1.3rem; /* Upgraded 50% from 0.85rem! */
    font-weight: bold;
    border-radius: 6px;
    cursor: pointer;
    transition: all 0.2s ease;

    &:hover {
      background: rgba(248, 113, 113, 0.1);
      border-color: #f87171;
      color: #ffffff;
      box-shadow: 0 0 15px rgba(248, 113, 113, 0.25);
    }
  }
}

/* Immersive Middle Content (2fr 1fr) */
.immersive-content-grid {
  flex: 1;
  display: grid;
  grid-template-columns: 2fr 1fr;
  align-items: stretch;
  gap: 24px;
  padding: 24px;
  min-height: 0; /* Important for flex-child scrolling */
  box-sizing: border-box;

  @media (max-width: 1023px) {
    grid-template-columns: 1fr;
    grid-template-rows: 3fr 2fr;
    gap: 16px;
    padding: 16px;
  }

  &[data-presentation='centered-gallery'] {
    grid-template-columns: minmax(0, 1fr);
    justify-items: center;

    @media (max-width: 1023px) {
      grid-template-rows: 1fr;
    }

    .immersive-col-left {
      width: min(100%, 120rem);
    }
  }
}

.immersive-col-left {
  min-width: 0;
  min-height: 0;
  display: flex;
  flex-direction: column;
  height: 100%;

  :deep(#comic-reader) {
    height: 100% !important;
    min-height: 0;
    display: flex;
    flex-direction: column;
    justify-content: center;
    margin: 0;
    max-width: 100%;
    padding: 0;
  }

  :deep(.page-flip-comic-layout) {
    height: 100%;
    min-height: 0;
    display: flex;
    flex-direction: column;
    justify-content: space-between;
    gap: 12px;
  }

  :deep(.comic-viewport) {
    flex: 1;
    min-height: 0 !important;
    max-height: calc(100vh - 270px); /* Upgraded subtraction for 80px header + 140px footer + padding */
    width: 100%;
    max-width: 100%;
    border-color: rgba(102, 179, 255, 0.35);
  }
}

.immersive-col-right {
  min-width: 0;
  height: 100%;
  display: flex;
  flex-direction: column;
  overflow: hidden;
  min-height: 0;

  /* 1.5x typography scale-up for all lore column elements when in immersive mode */
  :deep(.dispatch-plan-content) {
    background: linear-gradient(180deg, rgba(16, 21, 31, 0.45) 0%, rgba(12, 16, 22, 0.45) 100%) !important;
    backdrop-filter: blur(12px) !important;
    border: 1px solid rgba(102, 179, 255, 0.2) !important;

    .dispatch-plan-command {
      font-size: 1.35rem !important;
    }
    .title-h2 {
      font-size: 1.85rem !important;
    }
    .title-p {
      font-size: 1.25rem !important;
    }
  }

  :deep(.conversation-heading) {
    font-size: 1.35rem !important;
  }
  :deep(.conversation-title) {
    font-size: 1.95rem !important;
  }
  :deep(.conversation-message-header) {
    font-size: 1.35rem !important;
  }
  :deep(.conversation-message p) {
    font-size: 1.7rem !important;
  }
  :deep(.conversation-source) {
    font-size: 1.25rem !important;
    a {
      font-size: 1.25rem !important;
    }
  }
  :deep(.lore-quote-text) {
    font-size: 1.85rem !important;
  }
  :deep(.lore-quote-meta) {
    font-size: 1.35rem !important;
    strong {
      font-size: 1.45rem !important;
    }
  }

  :deep(.dispatch-quote-section) {
    height: 100% !important;
    display: flex;
    flex-direction: column;
  }

  :deep(.dispatch-quote-card) {
    height: 100% !important;
    display: flex;
    flex-direction: column;
    overflow: hidden;
    background-color: rgba(16, 21, 31, 0.45) !important;
    backdrop-filter: blur(12px) !important;
    border: 1px solid rgba(102, 179, 255, 0.25) !important;
  }

  :deep(.quote-viewport) {
    flex: 1;
    overflow-y: auto;
    /* Custom thin scrollbar */
    &::-webkit-scrollbar {
      width: 4px;
    }
    &::-webkit-scrollbar-track {
      background: transparent;
    }
    &::-webkit-scrollbar-thumb {
      background: rgba(102, 179, 255, 0.2);
      border-radius: 2px;
    }
    &::-webkit-scrollbar-thumb:hover {
      background: rgba(102, 179, 255, 0.4);
    }
  }
}

/* Immersive Bottom HUD Footer */
.immersive-hud-footer {
  height: 140px;
  border-top: 1px solid rgba(102, 179, 255, 0.2);
  background: rgba(16, 21, 31, 0.45);
  backdrop-filter: blur(12px);
  padding: 0 24px;
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 24px;
  flex-shrink: 0;
  position: relative; /* For absolute announcement area */

  @media (max-width: 767px) {
    height: auto;
    padding: 16px;
    flex-direction: column;
    gap: 16px;
  }
}

/* Mascot Telemetry Circle Console */
.mascot-console-hud {
  position: absolute;
  bottom: 140px; /* Floats above the larger footer controls bar */
  left: 32px;
  z-index: 110;
  display: flex;
  align-items: center;
  gap: 12px;
  background: rgba(12, 16, 22, 0.75);
  border: 1px solid rgba(102, 179, 255, 0.35);
  padding: 10px 14px;
  border-radius: 12px;
  box-shadow: 0 8px 32px rgba(0, 0, 0, 0.6);
  backdrop-filter: blur(12px);
  pointer-events: none; /* Allows clicks to pass through if it overlaps comic elements */

  @media (max-width: 1023px) {
    position: static;
    margin-top: 12px;
    align-self: center;
    background: transparent;
    border: none;
    box-shadow: none;
    backdrop-filter: none;
  }

  .mascot-console-ring {
    position: relative;
    width: 120px; /* Upgraded to 120px! Much larger. */
    height: 120px; /* Upgraded to 120px! Much larger. */
    border: 1px solid rgba(102, 179, 255, 0.5);
    background: rgba(9, 13, 22, 0.85);
    padding: 6px;
    box-sizing: border-box;
    display: flex;
    align-items: center;
    justify-content: center;
    box-shadow: 0 0 15px rgba(102, 179, 255, 0.25);
    border-radius: 8px; /* Square/rectangular grid HUD look */
  }

  .mascot-display-area {
    width: 100%;
    height: 100%;
    border-radius: 4px;
    overflow: hidden;
    position: relative;
    display: flex;
    align-items: center;
    justify-content: center;
  }

  .mascot-avatar {
    width: 100%;
    height: 100%;
    object-fit: contain; /* Do not crop the beautiful dinosaur images! */
    position: absolute;
    top: 0;
    left: 0;
    transition: opacity 1s ease-in-out;

    &.fading-out {
      opacity: 0;
    }
    &.fading-in {
      animation: mascotFadeIn 1s ease-in-out forwards;
    }
  }

  .hud-ring-overlay {
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    border-radius: 4px;
    box-shadow: inset 0 0 8px rgba(0, 0, 0, 0.5);
    pointer-events: none;
  }

  .mascot-telemetry-text {
    display: flex;
    flex-direction: column;
    font-size: 0.75rem;
    font-weight: bold;
    letter-spacing: 0.05em;
    color: #94a3b8;
    line-height: 1.3;
  }
}

@keyframes mascotFadeIn {
  from {
    opacity: 0;
  }
  to {
    opacity: 1;
  }
}

/* Soundtrack Dock Row Customization */
.immersive-soundtrack-dock {
  flex: 1;
  min-width: 450px;
  max-width: 900px;
  z-index: 20; /* Keep it clickable over the absolute announcement */

  @media (max-width: 767px) {
    width: 100%;
    min-width: unset;
  }
}

/* Scoped override styles within immersive mode footer */
.immersive-hud-footer {
  :deep(.sidebar-soundtrack-card) {
    background: transparent !important;
    border: none !important;
    box-shadow: none !important;
    padding: 0 !important;
    width: 100%;

    .soundtrack-panel {
      background: transparent !important;
      border: none !important;
      box-shadow: none !important;
      overflow: visible !important;
      display: flex;
      flex-direction: row;
      align-items: center;
      justify-content: center;
      gap: 16px;
      width: 100%;
    }

    .soundtrack-panel-main {
      padding: 0 !important;
      display: flex !important;
      flex-direction: row !important;
      align-items: center !important;
      justify-content: space-between !important;
      gap: 24px !important;
      width: 100%;

      @media (max-width: 900px) {
        grid-template-columns: auto 1fr auto !important;
        align-items: center !important;
      }
    }

    .soundtrack-lyrics-panel,
    .soundtrack-mobile-bar {
      display: none !important;
    }

    .soundtrack-artwork-shell {
      display: block !important;
      width: 66px !important; /* Upgraded 50% from 44px */
      height: 66px !important; /* Upgraded 50% from 44px */
      border-radius: 8px !important;
      flex-shrink: 0 !important;
    }

    .soundtrack-label {
      display: block !important;
      font-size: 1rem !important; /* Upgraded 50% from 0.65rem */
      letter-spacing: 0.1em !important;
      color: rgba(102, 179, 255, 0.7) !important;
    }

    .soundtrack-status {
      display: block !important;
      font-size: 1.1rem !important; /* Upgraded 50% from 0.72rem */
      color: rgba(148, 163, 184, 0.75) !important;
      line-height: 1.3 !important;
      max-width: 48ch !important;
      white-space: nowrap !important;
      overflow: hidden !important;
      text-overflow: ellipsis !important;
    }

    .soundtrack-links {
      display: flex !important;
      flex-direction: row !important;
      gap: 12px !important;
      margin-top: 2px !important;
      font-size: 1.1rem !important; /* Upgraded 50% from 0.72rem */
      align-items: center !important;

      .soundtrack-link {
        font-size: 1.1rem !important; /* Upgraded 50% from 0.72rem */
      }
      .soundtrack-premium-note {
        display: none !important;
      }
    }

    .soundtrack-copy {
      display: flex !important;
      flex-direction: column !important;
      gap: 2px !important;
      text-align: left !important;
      flex: 1 !important;
      min-width: 0 !important;
    }

    .soundtrack-title {
      font-size: 1.42rem !important; /* Upgraded 50% from 0.95rem */
      font-weight: bold !important;
      margin: 0 !important;
      display: -webkit-box !important;
      -webkit-line-clamp: 2 !important;
      -webkit-box-orient: vertical !important;
      white-space: normal !important;
      overflow: hidden !important;
    }

    .soundtrack-artist {
      font-size: 1.125rem !important; /* Upgraded 50% from 0.75rem */
      color: rgba(102, 179, 255, 0.8) !important;
      margin: 0 !important;
    }

    .soundtrack-controls-group {
      display: flex !important;
      flex-direction: row !important;
      align-items: center !important;
      gap: 12px !important; /* Slightly increased gap for larger buttons */
      margin: 0 !important;
      flex-shrink: 0 !important;
    }

    .quote-nav-btn,
    .soundtrack-skip-btn {
      width: 54px !important; /* Upgraded 50% from 36px */
      height: 54px !important; /* Upgraded 50% from 36px */
      font-size: 1.65rem !important; /* Upgraded 50% from 1.1rem */
    }

    .soundtrack-action {
      min-height: 54px !important; /* Upgraded 50% from 36px */
      height: 54px !important; /* Upgraded 50% from 36px */
      padding: 0 24px !important; /* Adjusted padding for larger text */
      font-size: 1.2rem !important; /* Upgraded 50% from 0.8rem */
    }
  }
}

/* Comic Autoplay Toggle Button */
.immersive-autoplay-btn {
  background: #10151f;
  border: 1px solid rgba(102, 179, 255, 0.25);
  color: #a0aec0;
  font-size: 1.2rem; /* Upgraded 50% from 0.78rem */
  font-weight: bold;
  padding: 6px 12px;
  border-radius: 6px;
  cursor: pointer;
  display: inline-flex;
  align-items: center;
  gap: 6px;
  transition: all 0.2s ease;
  letter-spacing: 0.05em;
  margin-bottom: 4px;

  &:hover {
    border-color: rgba(102, 179, 255, 0.5);
    color: #ffffff;
  }

  &.is-active {
    border-color: #27c93f;
    color: #27c93f;
    box-shadow: 0 0 10px rgba(39, 201, 63, 0.2);

    .hud-indicator-dot-mini {
      background-color: #27c93f;
      box-shadow: 0 0 6px #27c93f;
    }
  }

  .hud-indicator-dot-mini {
    width: 6px;
    height: 6px;
    border-radius: 50%;
    background-color: #5d5d5d;
    transition: all 0.2s ease;
  }
}

/* Announcement Area */
.hud-announcement-area {
  display: flex;
  align-items: center;
  justify-content: center;
  padding: 0 16px;
  overflow: hidden;
  height: 110px;
  width: 100%;
  max-width: 400px;
  border: 1px dashed rgba(102, 179, 255, 0.15);
  border-radius: 4px;
  background: rgba(16, 21, 31, 0.3);
  z-index: 10;

  @media (max-width: 1200px) {
    max-width: 250px;
  }

  @media (max-width: 1023px) {
    display: none;
  }

  .announcement-standby {
    font-size: 0.85rem;
    letter-spacing: 0.1em;
    opacity: 0.5;
  }

  .announcement-message {
    font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono', 'Courier New', monospace;
    font-size: clamp(1.1rem, 1.8vw, 1.4rem);
    font-style: normal;
    font-weight: 900;
    color: #ffffff;
    text-shadow:
      0 0 15px rgba(255, 255, 255, 0.4),
      0 0 5px rgba(102, 179, 255, 0.8);
    white-space: nowrap;
    overflow: hidden;
    text-overflow: ellipsis;
    text-align: center;
    width: 100%;

    .cursor {
      animation: blink 1s step-end infinite;
      margin-left: 2px;
    }
  }
}

@keyframes blink {
  0%,
  100% {
    opacity: 1;
  }
  50% {
    opacity: 0;
  }
}

.flicker-glitch-enter-active,
.flicker-glitch-leave-active {
  transition: opacity 0.3s ease;
}
.flicker-glitch-enter-from,
.flicker-glitch-leave-to {
  opacity: 0;
}
.flicker-glitch-enter-active {
  animation: flicker-in 1.2s ease-in-out forwards;
}

@keyframes flicker-in {
  0% {
    opacity: 0;
    text-shadow: none;
  }
  10% {
    opacity: 1;
    text-shadow: 0 0 8px rgba(0, 255, 255, 0.8);
  }
  15% {
    opacity: 0;
  }
  25% {
    opacity: 1;
    text-shadow: none;
  }
  35% {
    opacity: 0.5;
  }
  45% {
    opacity: 1;
    text-shadow: 0 0 12px rgba(0, 255, 255, 0.9);
  }
  60% {
    opacity: 0.8;
  }
  80% {
    opacity: 1;
  }
  90% {
    opacity: 0.9;
  }
  100% {
    opacity: 1;
    text-shadow: 0 0 8px rgba(0, 255, 255, 0.4);
  }
}

/* Right Telemetry Column */
.hud-right-telemetry {
  display: flex;
  flex-direction: column;
  gap: 6px;
  align-items: flex-end;
  text-align: right;
  flex-shrink: 0;

  @media (max-width: 767px) {
    align-self: flex-end;
  }

  .decryption-mini-meter {
    width: 140px;
    display: flex;
    flex-direction: column;
    gap: 4px;
  }

  .meter-header-mini {
    display: flex;
    justify-content: space-between;
    font-size: 0.65rem;
    font-weight: bold;
    color: #888888;
  }

  .meter-bar-mini {
    height: 3px;
    background-color: #0c1016;
    border-radius: 1.5px;
    overflow: hidden;
    border: 1px solid rgba(102, 179, 255, 0.1);
  }

  .meter-fill-mini {
    height: 100%;
    width: 7%;
    background-color: #66b3ff;
    border-radius: 1.5px;
    box-shadow: 0 0 6px rgba(102, 179, 255, 0.5);
  }

  .hud-telemetry-coords {
    font-size: 0.68rem;
    font-weight: bold;
    color: #616161;
    letter-spacing: 0.05em;
  }
}

/* Custom Fast Pulse Utility */
.animate-pulse-fast {
  animation: pulseFast 1.2s cubic-bezier(0.4, 0, 0.6, 1) infinite;
}

@keyframes pulseFast {
  0%,
  100% {
    opacity: 1;
  }
  50% {
    opacity: 0.35;
  }
}

.equinox-overlay {
  position: absolute;
  top: 80px; /* HUD header offset */
  bottom: 140px; /* HUD footer offset */
  left: 0;
  width: 100vw;
  z-index: 105;
  display: flex;
  align-items: center;
  justify-content: center;
  background-color: rgba(12, 16, 22, 0.4);
  backdrop-filter: blur(4px);
  pointer-events: none;
}

.equinox-title-wrap {
  text-align: center;
  max-width: 800px;
  padding: 32px;
}

.equinox-label {
  font-size: 1.4rem;
  font-weight: bold;
  letter-spacing: 0.15em;
  margin-bottom: 16px;
}

.equinox-track-title {
  font-size: clamp(2.5rem, 5vw, 4.5rem);
  font-weight: 900;
  text-transform: uppercase;
  color: #ffffff;
  letter-spacing: -0.01em;
  margin: 0 0 12px;
}

.equinox-track-artist {
  font-size: 1.6rem;
  letter-spacing: 0.08em;
  text-transform: uppercase;
}

/* Vue equinox-fade transitions */
.equinox-fade-enter-active,
.equinox-fade-leave-active {
  transition: opacity 1.5s ease-in-out;
}

.equinox-fade-enter-from,
.equinox-fade-leave-to {
  opacity: 0;
}
</style>
